spring:
  datasource:
    url: jdbc:h2:mem:experiencedb;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true

jwt:
  secret: ${JWT_SECRET:my-super-secret-key-for-local-development-only-32bytes}
  access-token-expiry: 1800000
  refresh-token-expiry: 604800000

crawling:
  enabled: true
  mock-enabled: false
  schedule-cron: "0 0 * * * *"
  max-pages-per-site: 10
  delay-min-ms: 1000
  delay-max-ms: 2000
  connection-timeout-ms: 10000
  read-timeout-ms: 30000
  user-agent: "ExperiencePlatformBot/1.0 (+https://example.com/bot)"
  detail-fetch-enabled: true
  detail-fetch-delay-ms: 500
  parallel-threads: 5
  reve-api-token: ${REVE_API_TOKEN:}
  reve-username: ${REVE_USERNAME:qjsro1204@naver.com}
  reve-password: ${REVE_PASSWORD:Wjddyd!0619}
  reviewnote-fid-token: ${REVIEWNOTE_FID_TOKEN:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJQQkIwU3F6bnB5T1NkbGh0TDU2bjkxbERUQTIzIiwiaWF0IjoxNzc0MTg5MzE3fQ.WK1XJWBnpBqltUvhmEvCoAtyy-1vPJK4GKZdnq-gsTE}
  reviewnote-session: ${REVIEWNOTE_SESSION:Fe26.2*1*9cfccdef3f651a3215706afad1b0c39a96e55d34da5aeeb80b7b5ee99cd334e9*a-DFYi5daSki242t_FwvVQ*ZigJIo3fNM30rwN6JOrXA8hXWSQehxwVj_2z4L5NNkP81YHstrDwpx5yxf-0q0onYnjHUWhVl2HiW24cBAww08e2fUtr3kDJKV8K9P6NVhqV0YqCTDABNkRkaZMFaj_q*1775485317537*64c422a64dd18126da010a061676c1a86e48d308457be2de886d902910068301*gt3q2w6Rb3ZFFFylezDK61HmGA6nUQOA5FVJ6OgraH8}
